"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-20 14:35:32.092575

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_meta",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("mime", sa.String(length=80), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("tags", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("media_uuid", sa.String(length=64), nullable=True),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column("media_uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index("ix_assets_kind", ["kind"], unique=False)
        batch_op.create_index("ux_assets_filename", ["filename"], unique=True)
        batch_op.create_index("ux_assets_sha256", ["sha256"], unique=True)

    op.create_table(
        "catalog_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("air", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("creator", sa.String(length=80), nullable=True),
        sa.Column("architecture", sa.String(length=80), nullable=True),
        sa.Column("capabilities_json", sa.JSON(), nullable=False),
        sa.Column("default_width", sa.Integer(), nullable=True),
        sa.Column("default_height", sa.Integer(), nullable=True),
        sa.Column("default_steps", sa.Integer(), nullable=True),
        sa.Column("default_cfg", sa.Float(), nullable=True),
        sa.Column("hero_image_url", sa.String(length=500), nullable=True),
        sa.Column("price_unit", sa.String(length=16), nullable=True),
        sa.Column("price_primary", sa.Float(), nullable=True),
        sa.Column("price_in", sa.Float(), nullable=True),
        sa.Column("price_out", sa.Float(), nullable=True),
        sa.Column("price_tiers_json", sa.JSON(), nullable=True),
        sa.Column("price_source", sa.String(length=16), nullable=True),
        sa.Column("price_updated_at", sa.DateTime(), nullable=True),
        sa.Column("provider_settings_schema", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("catalog_models", schema=None) as batch_op:
        batch_op.create_index("ix_catalog_kind", ["kind"], unique=False)
        batch_op.create_index("ux_catalog_air", ["air"], unique=True)

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_image_model", sa.String(length=120), nullable=True),
        sa.Column("default_video_model", sa.String(length=120), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index("ux_projects_slug", ["slug"], unique=True)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("form_json", sa.JSON(), nullable=False),
        sa.Column("composed_prompt", sa.Text(), nullable=False),
        sa.Column("final_prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=False),
        sa.Column("polish_json", sa.JSON(), nullable=True),
        sa.Column("final_edited", sa.Boolean(), nullable=False),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.create_index("ix_prompts_fav", ["is_favourite"], unique=False)
        batch_op.create_index("ix_prompts_project", ["project_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("model_air", sa.String(length=120), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("task_json", sa.JSON(), nullable=True),
        sa.Column("dropped_params_json", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("status_text", sa.String(length=200), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("runware_task_uuid", sa.String(length=64), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_model", ["model_air"], unique=False)
        batch_op.create_index("ix_jobs_project_created", ["project_id", "created_at"], unique=False)
        batch_op.create_index("ix_jobs_status", ["status"], unique=False)

    op.create_table(
        "outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("filename", sa.String(length=80), nullable=False),
        sa.Column("rel_path", sa.String(length=300), nullable=False),
        sa.Column("sidecar_rel_path", sa.String(length=300), nullable=False),
        sa.Column("model_air", sa.String(length=120), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=False),
        sa.Column("params_json", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("source_url", sa.String(length=600), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.Column("is_missing", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outputs", schema=None) as batch_op:
        batch_op.create_index("ix_outputs_fav", ["is_favourite"], unique=False)
        batch_op.create_index("ix_outputs_job", ["job_id"], unique=False)
        batch_op.create_index("ix_outputs_model", ["model_air"], unique=False)
        batch_op.create_index(
            "ix_outputs_project_created", ["project_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ux_outputs_project_filename", ["project_id", "filename"], unique=True
        )

    op.create_table(
        "usage_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("task_type", sa.String(length=30), nullable=False),
        sa.Column("model_air", sa.String(length=120), nullable=True),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_entries", schema=None) as batch_op:
        batch_op.create_index("ix_usage_day", ["day"], unique=False)
        batch_op.create_index("ix_usage_project_day", ["project_id", "day"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_project_day")
        batch_op.drop_index("ix_usage_day")

    op.drop_table("usage_entries")
    with op.batch_alter_table("outputs", schema=None) as batch_op:
        batch_op.drop_index("ux_outputs_project_filename")
        batch_op.drop_index("ix_outputs_project_created")
        batch_op.drop_index("ix_outputs_model")
        batch_op.drop_index("ix_outputs_job")
        batch_op.drop_index("ix_outputs_fav")

    op.drop_table("outputs")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status")
        batch_op.drop_index("ix_jobs_project_created")
        batch_op.drop_index("ix_jobs_model")

    op.drop_table("jobs")
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.drop_index("ix_prompts_project")
        batch_op.drop_index("ix_prompts_fav")

    op.drop_table("prompts")
    op.drop_table("settings")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ux_projects_slug")

    op.drop_table("projects")
    with op.batch_alter_table("catalog_models", schema=None) as batch_op:
        batch_op.drop_index("ux_catalog_air")
        batch_op.drop_index("ix_catalog_kind")

    op.drop_table("catalog_models")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("ux_assets_sha256")
        batch_op.drop_index("ux_assets_filename")
        batch_op.drop_index("ix_assets_kind")

    op.drop_table("assets")
    op.drop_table("app_meta")
    # ### end Alembic commands ###
