"""phase3

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-20 17:52:26.736481

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("expected_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("seen_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("title", sa.String(length=120), nullable=True))

    with op.batch_alter_table("outputs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("thumb_rel_path", sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outputs", schema=None) as batch_op:
        batch_op.drop_column("thumb_rel_path")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("title")
        batch_op.drop_column("seen_at")
        batch_op.drop_column("expected_ms")

    # ### end Alembic commands ###
