"""phase4

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-20 20:01:57.841960

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index("ix_assets_tags", ["tags"], unique=False)

    with op.batch_alter_table("outputs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("poster_rel_path", sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outputs", schema=None) as batch_op:
        batch_op.drop_column("poster_rel_path")

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("ix_assets_tags")

    # ### end Alembic commands ###
