"""phase5

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-20 22:21:20.406560

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        # server_default backfills existing rows (SQLite refuses a NOT NULL column with
        # no default on a non-empty table); the model's own default (used for new rows
        # inserted via the ORM) is Python-side and unaffected by this.
        batch_op.add_column(
            sa.Column("tags", sa.String(length=400), nullable=False, server_default=",")
        )
        batch_op.add_column(
            sa.Column("content_hash", sa.String(length=64), nullable=False, server_default="")
        )
        batch_op.create_index("ix_prompts_hash", ["project_id", "content_hash"], unique=False)
        batch_op.create_index("ix_prompts_tags", ["tags"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.drop_index("ix_prompts_tags")
        batch_op.drop_index("ix_prompts_hash")
        batch_op.drop_column("content_hash")
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
